/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XFILE_H_RPCGEN
#define _RPC_XFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_VIEW 6

struct InputView {
	char tipo[6];
};
typedef struct InputView InputView;

struct Prenotazione {
	char targa[7];
	char patente[5];
	char tipo[6];
	char folder[12];
};
typedef struct Prenotazione Prenotazione;

struct OutputView {
	Prenotazione prenotazioni[MAX_VIEW];
	int size;
};
typedef struct OutputView OutputView;

struct InputAggiornamento {
	char targa[7];
	char new_patente[5];
};
typedef struct InputAggiornamento InputAggiornamento;

#define XFILES 0x20000013
#define XFILESVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define VISUALIZZA_PRENOTAZIONI 1
extern  OutputView * visualizza_prenotazioni_1(InputView *, CLIENT *);
extern  OutputView * visualizza_prenotazioni_1_svc(InputView *, struct svc_req *);
#define AGGIORNA_LICENZA 2
extern  int * aggiorna_licenza_1(InputAggiornamento *, CLIENT *);
extern  int * aggiorna_licenza_1_svc(InputAggiornamento *, struct svc_req *);
extern int xfiles_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define VISUALIZZA_PRENOTAZIONI 1
extern  OutputView * visualizza_prenotazioni_1();
extern  OutputView * visualizza_prenotazioni_1_svc();
#define AGGIORNA_LICENZA 2
extern  int * aggiorna_licenza_1();
extern  int * aggiorna_licenza_1_svc();
extern int xfiles_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_InputView (XDR *, InputView*);
extern  bool_t xdr_Prenotazione (XDR *, Prenotazione*);
extern  bool_t xdr_OutputView (XDR *, OutputView*);
extern  bool_t xdr_InputAggiornamento (XDR *, InputAggiornamento*);

#else /* K&R C */
extern bool_t xdr_InputView ();
extern bool_t xdr_Prenotazione ();
extern bool_t xdr_OutputView ();
extern bool_t xdr_InputAggiornamento ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_XFILE_H_RPCGEN */
